### ISSUE TITLE
A build error occurred:error[E0277]: `[u8; 2]` is not an iterator

### ISSUE THREAD

**Issue by harlanc** [webrtc-rs/rtp#16]
- My rustc version is :
rustc 1.48.0 (7eac88abb 2020-11-16)

- My OS platform is:
macOS Big Sur

The following error happens:

    stap_a_nalu.extend(sps_len);
   |                                ^^^^^^^
   |                                |
   |                                expected an implementor of trait `IntoIterator`
   |                                help: consider borrowing here: `&sps_len`
   |

**Comment by rainliu** [comment]
upgrade your rustc to 1.53+  (https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html#intoiterator-for-arrays)

**Comment by harlanc** [comment]
I upgraded the rust version to rustc 1.55.0 (c8dfcfe04 2021-09-06) and the build passed, thx.
