### ISSUE TITLE
Overflow on long-running TrackLocal

### ISSUE THREAD

**Issue by jaymell** [webrtc-rs/rtp#19]
I'm finding that long-running video streams eventually panic with the following error due to the packetizer's timestamp attribute overflowing:

`thread 'tokio-runtime-worker' panicked at 'attempt to add with overflow', registry/src/github.com-1ecc6299db9ec823/rtp-0.6.1/src/packetizer/mod.rs:138:9`

which is this line of code in the packetizer:
```
self.timestamp += samples;
```

I wouldn't mind researching a better solution here if needed but am wondering if just using a Wrapping type to allow addition with overflow would allow rollover without breaking clients?

**Comment by rainliu** [comment]
wrapping_add should be fine for self.timestamp.

Could you submit a PR to fix it?

**Comment by jaymell** [comment]
Sure, will raise something in next couple days. Thanks for the prompt response.

**Comment by rainliu** [comment]
@jaymell, actually the following commit https://github.com/webrtc-rs/rtp/commit/7b2b695ebebd312ea344218e6909199baa6c3e30#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26 fix your change.
