### ISSUE TITLE
padding included in payload

### ISSUE THREAD

**Issue by scottlamb** [webrtc-rs/rtp#9]
`impl Marshaller for Packet` doesn't consider padding:

*   `unmarshal` shouldn't include the padding bytes in the new `Packet`'s `payload`
*   `marshal_size` and `marshal_to` then also need to change to add in padding bytes

https://github.com/webrtc-rs/rtp/blob/54d15791f43a0e9495edc016f44b8b8ccc172908/src/packet/mod.rs#L33-L52

**Comment by metaclips** [comment]
I'll be taking this up @scottlamb @rainliu. This might be a breaking change, which is a fun thing :))

**Comment by metaclips** [comment]
@scottlamb mind sharing a test that fails due to this issue?

**Comment by metaclips** [comment]
@scottlamb @rainliu  I really don't think this issue has been fixed completely so I'll be reopening, do indicate if its been solved.

**Comment by scottlamb** [comment]
> do indicate if its been solved

I don't know, sorry. I switched to the `rtp-rs` crate after hitting this. `rtp-rs` already had correct padding handling and looked more efficient (less reference-counting due to `Bytes` cloning, no `Vec` allocations) although I didn't actually benchmark.

**Comment by metaclips** [comment]
🥲 too bad. Should work on a fix and also improve performance this weekend. Do hope you get to using this library again when it's fixed!.
